repos:
  # Git Commit Hook and Common File Formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: ['--unsafe']  # Will not automatically commit changes after formatting

  # Sorting imports and Removing Unused Imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # Black Formatting
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
          - --include='\.py?$'
          - --exclude=\.*

  # Autoflake
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
