name: Deploy Serverless FastAPI to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check node
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt            

      - name: Run Pytest
        run: |
          python -m pytest

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash       

      - name: Install Azure Functions Core Tools
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update -y
          sudo apt-get install azure-functions-core-tools-4 -y

      - name: Log in to Azure
        run: |
          az login --service-principal \
          -t ${{ secrets.AZURE_TENANT_ID }} \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }}          

      - name: Create Storage Account
        run: |
          az storage account create \
          --name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --location japaneast \
          --sku Standard_LRS        

      - name: Create Function App
        run: |
          az functionapp create \
          --consumption-plan-location japaneast \
          --runtime python \
          --runtime-version 3.11 \
          --functions-version 4 \
          --name demo-fastapi-serverless \
          --os-type linux \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --storage-account ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}        

      - name: Publish Function App
        run: |
          func azure functionapp publish ${{ secrets.AZURE_FUNCTION_APP_NAME }}        

